<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="LAPTOP-CO6KFNG0" name="com.qa.tests.LoginTests" tests="4" failures="0" timestamp="2022-03-27T00:29:53 IST" time="0.095" errors="1">
  <testcase name="invalidPassord" time="0.000" classname="com.qa.tests.LoginTests">
    <skipped/>
  </testcase> <!-- invalidPassord -->
  <system-out/>
  <testcase name="setup" time="0.095" classname="com.qa.tests.LoginTests">
    <error type="java.lang.IllegalStateException" message="The driver executable does not exist: C:\usr\local\bin\node">
      <![CDATA[java.lang.IllegalStateException: The driver executable does not exist: C:\usr\local\bin\node
at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:146)
at org.openqa.selenium.remote.service.DriverService$Builder.usingDriverExecutable(DriverService.java:281)
at io.appium.java_client.service.local.AppiumServiceBuilder.usingDriverExecutable(AppiumServiceBuilder.java:427)
at com.qa.BaseTest.getAppiumService(BaseTest.java:106)
at com.qa.BaseTest.setup(BaseTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setup -->
  <system-out/>
  <testcase name="invalidUserName" time="0.000" classname="com.qa.tests.LoginTests">
    <skipped/>
  </testcase> <!-- invalidUserName -->
  <system-out/>
  <testcase name="validUser" time="0.000" classname="com.qa.tests.LoginTests">
    <skipped/>
  </testcase> <!-- validUser -->
  <system-out/>
</testsuite> <!-- com.qa.tests.LoginTests -->
